### ISSUE TITLE
MainLayout调用Modal没效果

### ISSUE THREAD

**Issue by angyhuang** [ArgoZhang/BootstrapBlazor#20]
请教下，在MainLayout.razor上调用DialogService的Show事件不会弹出对话框，源码跟踪到是Dialog.razor里的ModalDialog没有映射出来，因此抛出空对象异常；其他地方调用DialogService的Show事件可以正常弹出对话框

**Comment by ArgoZhang** [comment]
感谢提出 Issue，能否加一下群，方便交流。这里我很卡，很难上来这里回答问题

**Comment by angyhuang** [comment]
有幸得到大佬的回复，可以加群，加哪个群？

**Comment by ArgoZhang** [comment]
QQ 群号：795206915


欢迎大佬加群


| |
Argo
|
|
argo@163.com
|
签名由网易邮箱大师定制


在2020年11月10日 11:14，angyhuang<notifications@github.com> 写道：

有幸得到大佬的回复，可以加群，加哪个群？
