### ISSUE TITLE
bug:固定列功能demo, 鼠标光标所在行滚动会穿透.

### ISSUE THREAD

**Issue by densen2014** [ArgoZhang/BootstrapBlazor#23]
所在页面 
[重现视频.zip](https://github.com/ArgoZhang/BootstrapBlazor/files/5563085/default.zip)
https://blazor.sdgxgz.com/tables/fix-column

**Comment by DavidStrive** [comment]
我刚才也遇到这个问题 下滚动条往右拖 鼠标光标所在行 隐藏在固定行下的文字会显示出来

**Comment by ArgoZhang** [comment]
had fixed
