### ISSUE TITLE
已将此库收入于awesome-dotnet-cn

### ISSUE THREAD

**Issue by tonyqus** [ArgoZhang/BootstrapBlazor#28]
见https://github.com/dotnet-cn/awesome-dotnet-cn/blob/master/README.md

**Comment by densen2014** [comment]
翻到最下面终于见到了

**Comment by tonyqus** [comment]
这是分类排序的关系，先后不影响项目重要性。

alex chow <notifications@github.com> 于2020年11月28日周六 上午5:13写道：
