### ISSUE TITLE
怎么设置font

### ISSUE THREAD

**Issue by chenlei620** [ArgoZhang/BootstrapBlazor#31]
你好，编译出来的bootstrap.blazor.css里设定的font：
html, body, button, .popover {
    font-family: Helvetica Neue,Helvetica,PingFang SC,Hiragino Sans GB,Microsoft YaHei,SimSun,sans-serif;
}
我想设置别的font，请教一下在代码里能实现自己重设font吗？要不然每次编译之后font都是上面这样的，每次都得手改。
谢谢！

**Comment by ArgoZhang** [comment]
自己写一个 css 文件  _Host.cshtml 文件中引用这个 css 文件就可以啦
