### ISSUE TITLE
使用 Layout布局之后，激活模态框时，黑色背景跑到顶层了

### ISSUE THREAD

**Issue by Weisskunig** [ArgoZhang/BootstrapBlazor#5]
根据文档，把这段加入了site:
app {
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    bottom: 0;
    overflow: auto;
}
其它样式正常了，就是模态框激活的时候被背景遮住，导致什么都点不了。

**Comment by ZhuanOpt** [comment]
我也遇到过这个问题，去掉你site添加的这一段就好了，希望对你有用

**Comment by Weisskunig** [comment]
> 我也遇到过这个问题，去掉你site添加的这一段就好了，希望对你有用

问题是去掉那段，组件提供的layout布局就失效了。我认为这是一个bug。

**Comment by ArgoZhang** [comment]
感谢联系我，这里是备份仓库，主库是国内的 Gitee 仓库
